EvaShop/Controllers/HomeController.cs
using EvaShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using AutoMapper;
using EvaShop.Data;
using EvaShop.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace EvaShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _appDbContext;
        private readonly IMapper _mapper;

        public HomeController(ILogger<HomeController> logger, 
            ApplicationDbContext appDbContext,IMapper mapper)
        {
            _logger = logger;
            _appDbContext = appDbContext;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var inventarios = _appDbContext.Inventarios
                .Include(i=>i.Articulo)
                .ThenInclude(i=>i.SubCategoria)
                .ThenInclude(i=>i.Categoria)
                .Where(i=>i.Existencias > 0)
                .OrderBy(i=>i.PrecioDeVenta)
                .Take(3)
                .ToList();
            var result =  _mapper.Map<IEnumerable<InventarioViewModel>>(inventarios);
            return View(result);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult AboutUs()
        {
            return View();
        }
    }
}

EvaShop/Controllers/ManagerController.cs
using EvaShop.Services;
using Microsoft.AspNetCore.Mvc;

namespace CatalogoWebApp.Controllers
{
    public class ManagerController : Controller
    {
        private readonly IEmailSender _emailSender;
        private const string SessionKeyName = "_Name";
        private const string Error = "_Error";

        public ManagerController(IEmailSender emailSender)
        {
            _emailSender = emailSender;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(string user, string password)
        {
            if (user == "Admin" && password == "Catolica10")
            {
                HttpContext.Session.SetString(SessionKeyName, "Admin");
                return Redirect("/Inventarios");
            }
            HttpContext.Session.SetString(Error,"Usuario o contraseña incorrecta");
            return Redirect("/Home");

        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove(SessionKeyName);
            HttpContext.Session.Remove(Error);
            return Redirect("/Home");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Newsletter(string email)
        {
            const string msg = "<h1 style='text-align: center'>Felicidades tienes un descuento del 20%<h1>";
            return Redirect(_emailSender.Notify(msg, email) ? "/Home" : "/Contact");
        }

        //GET IN TOUCH
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult GetInTouch(string name,string email, string subject, string body)
        {
            var msg = email + ": " + body; 
            return Redirect(_emailSender.Notify(msg,_emailSender.GetEmail(),subject) ? "/Home" : "/Contact");
        }
    }
}

EvaShop/Controllers/ProductController.cs
using AutoMapper;
using EvaShop.Data;
using EvaShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EvaShop.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _appDbContext;
        private readonly IMapper _mapper;

        public ProductController(ApplicationDbContext appDbContext, IMapper mapper)
        {
            _appDbContext = appDbContext;
            _mapper = mapper;
        }
        public IActionResult Index(string id)
        {
            var articulo = _appDbContext.Inventarios
                .Include(i=>i.Articulo)
                .ThenInclude(i=>i.SubCategoria)
                .ThenInclude(i=>i.Categoria)
                .FirstOrDefault(i=> i.ArticuloId.ToString() == id);

            return View(_mapper.Map<InventarioViewModel>(articulo));
        }
    }
}

EvaShop/Views/Home/AboutUs.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="row" style="margin-top: 10%">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <h3 class="text-center" style="margin-bottom: 5%">QUIÉNES SOMOS</h3>
        <div class="text-justify">
            <p style="font-size: medium">
                EVA es una tienda de ropa interior femenina y masculina salvadoreña, ubicada en
                Santa Ana, que nace de la propuesta de dar a la mujer y al hombre elegancia,
                variedad, sensualidad, comodidad, y seguridad en su vestir, impactando
                positivamente en la autoestima. Para nosotros, la ropa interior significa mucho
                más que una prenda de vestir, representa nuestro estado de ánimo, la percepción,
                confianza y valoración que tenemos sobre nosotros mujer y hombres
                empoderados. Entendiendo que cuando nos amamos y aceptamos como somos
                no necesitamos ser perfectos o tener un cuerpo perfecto para sentirnos bien
                consigo mismo.
                Eva, ha creado un concepto basado en la necesidad de cuidarse, verse y sentirse
                bien. Ofreciendo una amplia gama de ropa interior femenina y masculina. Nuestra
                meta es que te conozcas, provocando Magia y enseñándote a descubrir las
                bondades innatas que cada ser humano tiene, simplemente conociendo tu cuerpo
                y proporcionándoles satisfacción y felicidad en sus compras.
                Es por eso que Eva, te invita a navegar en la web y realizar tus compras online,
                para todos esos momentos especiales de los cuales necesitas estar siempre y
                sentirte bien.
            </p>
            <h4>“Porque el secreto de tu confianza es sentirte bien con tu ropa interior”</h4>
        </div>
    </div>

</div>

EvaShop/Views/Home/Index.cshtml
@using CatalogoWebApp.Services
@model IEnumerable<EvaShop.ViewModels.InventarioViewModel>
@inject IPathResolver PathResolver
@{
	ViewData["Title"] = "Home Page";
}

<div class="home">
		
		<!-- Home Slider -->
		<div class="home_slider_container">
			<div class="owl-carousel owl-theme home_slider">
				
				<!-- Home Slider Item -->
				<div class="owl-item">
					<div class="home_slider_background" style="background-image:url(images/home_slider_1.jpg)"></div>
					<div class="home_slider_content">
						<div class="home_slider_content_inner">
							<div class="home_slider_subtitle">Precio de Promocion</div>
							<div class="home_slider_title">New Collection</div>
						</div>	
					</div>
				</div>

				<!-- Home Slider Item -->
				<div class="owl-item">
					<div class="home_slider_background" style="background-image:url(images/slider2.png)"></div>
					<div class="home_slider_content">
						<div class="home_slider_content_inner">
							<div class="home_slider_subtitle">Precio de Promocion</div>
							<div class="home_slider_title">New Collection</div>
						</div>	
					</div>
				</div>

				<!-- Home Slider Item -->
				<div class="owl-item">
					<div class="home_slider_background" style="background-image:url(images/slider3.png)"></div>
					<div class="home_slider_content">
						<div class="home_slider_content_inner">
							<div class="home_slider_subtitle">Precio de Promocion</div>
							<div class="home_slider_title">New Collection</div>
						</div>	
					</div>
				</div>

			</div>
			
			<!-- Home Slider Nav -->

			<div class="home_slider_next d-flex flex-column align-items-center justify-content-center"><img src="~/images/arrow_r.png" alt=""></div>

			<!-- Home Slider Dots -->

			@*<div class="home_slider_dots_container">
				<div class="container">
					<div class="row">
						<div class="col">
							<div class="home_slider_dots">
								<ul id="home_slider_custom_dots" class="home_slider_custom_dots">
									<li class="home_slider_custom_dot active">1<div></div></li>
									<li class="home_slider_custom_dot">2<div></div></li>
									<li class="home_slider_custom_dot">3<div></div></li>
								</ul>
							</div>
						</div>
					</div>
				</div>		
			</div>*@
		</div>
	</div>
	
<div class="promo">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="section_title_container text-center">
					<div class="section_subtitle">only the best</div>
					<div class="section_title">precios promocionales</div>
				</div>
			</div>
		</div>
		<div class="row promo_container">

			<!-- Promo Item -->
			<div class="col-lg-4 promo_col">
				<div class="promo_item">
					<div class="promo_image">
						<img src="~/images/promocion1.jpg" alt="">
					</div>
					<div class="promo_link"><a href="#">Shop Now</a></div>
				</div>
			</div>

			<!-- Promo Item -->
			<div class="col-lg-4 promo_col">
				<div class="promo_item">
					<div class="promo_image">
						<img src="~/images/promocion2.jpg" alt="">
						@*<div class="promo_content promo_content_2">
							<div class="promo_title"></div>
							<div class="promo_subtitle"></div>
						</div>*@
					</div>
					<div class="promo_link"><a href="#">Shop Now</a></div>
				</div>
			</div>

			<!-- Promo Item -->
			<div class="col-lg-4 promo_col">
				<div class="promo_item">
					<div class="promo_image">
						<img src="~/images/promocion3.jpg" alt="">
						@*<div class="promo_content promo_content_3">
							<div class="promo_title"></div>
							<div class="promo_subtitle"></div>
						</div>*@
					</div>
					<div class="promo_link"><a href="#">Shop Now</a></div>
				</div>
			</div>

		</div>
	</div>
</div>

<div class="arrivals">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="section_title_container text-center">
						<div class="section_subtitle">only the best</div>
						<div class="section_title">Recién llegados</div>
					</div>
				</div>
			</div>
			<div class="row products_container">
				@foreach (var item in Model)
				{
					<!-- Product -->
					<div class="col-lg-4 product_col">
						<div class="product">
							<div class="product_image">
								<img src="@PathResolver.GetUrl(@item.ArticuloImagenes)" alt="articulo">
							</div>
							<div class="rating rating_4">
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
							</div>
							<div class="product_content clearfix">
								<div class="product_info">
									<div class="product_name">
										<a asp-controller="Product" asp-action="Index" asp-route-id="@item.ArticuloId">@item.Articulo</a>
									</div>
									<div class="product_price">@item.PrecioDeVenta</div>
								</div>
							</div>
						</div>
					</div>
				}

			</div>
		</div>
	</div>

	<!-- Extra -->

	<div class="extra clearfix">
		<div class="extra_promo extra_promo_1">
			<div class="extra_promo_image" style="background-image:url(/images/banner1.jpg)"></div>
			<div class="extra_1_content d-flex flex-column align-items-center justify-content-center text-center">
				<div class="extra_1_price">30%<span>off</span></div>
				<div class="extra_1_title">En todos los bikinis</div>
				<div class="extra_1_text">Hasta el 20% de descuento en todas las prendas marcadas</div>
				<div class="button extra_1_button"><a href="#">check out</a></div>
			</div>
		</div>
		<div class="extra_promo extra_promo_2">
			<div class="extra_promo_image" style="background-image:url(/images/banner3.jpg)"></div>
			<div class="extra_2_content d-flex flex-column align-items-center justify-content-center text-center">
				<div class="extra_2_title">
					<div class="extra_2_center">&</div>
					<div class="extra_2_top">Mix</div>
					<div class="extra_2_bottom">Match</div>
				</div>
				<div class="extra_2_text"></div>
				<div class="button extra_2_button"><a href="#">check out</a></div>
			</div>
		</div>
	</div>

	<!-- Gallery -->

	<div class="gallery">
		<div class="gallery_image" style="background-image:url(images/gallery.jpg)"></div>
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="gallery_title text-center">
						<ul>
							<li><a href="#">#Eva</a></li>
							<li><a href="#">#Evainstagram</a></li>
							<li><a href="#">#Evagirl</a></li>
						</ul>
					</div>
					<div class="gallery_text text-center" style="font-size:25px">“Porque el secreto de tu confianza es sentirte bien con tu ropa interior”</div>
					<div class="button gallery_button"><a href="#">submit</a></div>
				</div>
			</div>
		</div>	
		<div class="gallery_slider_container">
			
			<!-- Gallery Slider -->
			<div class="owl-carousel owl-theme gallery_slider">
				
				<!-- Gallery Item -->
				<div class="owl-item gallery_item">
					<a class="colorbox" href="images/gallery_1.jpg">
						<img src="images/gallery_1.jpg" alt="">
					</a>
				</div>

				<!-- Gallery Item -->
				<div class="owl-item gallery_item">
					<a class="colorbox" href="images/gallery_2.jpg">
						<img src="images/gallery_2.jpg" alt="">
					</a>
				</div>

				<!-- Gallery Item -->
				<div class="owl-item gallery_item">
					<a class="colorbox" href="#">
						<img src="~/images/trajenegro.png" alt="">
					</a>
				</div>

				<!-- Gallery Item -->
				<div class="owl-item gallery_item">
					<a class="colorbox" href="~/images/gallery_4.jpg">
						<img src="~/images/gallery_4.jpg" alt="">
					</a>
				</div>

				<!-- Gallery Item -->
				<div class="owl-item gallery_item">
					<a class="colorbox" href="~/images/gallery_5.jpg">
						<img src="~/images/gallery_5.jpg" alt="">
					</a>
				</div>

				<!-- Gallery Item -->
				<div class="owl-item gallery_item">
					<a class="colorbox" href="~/images/gallery_6.jpg">
						<img src="~/images/gallery_6.jpg" alt="">
					</a>
				</div>

			</div>
		</div>	
	</div>

	<!-- Testimonials -->

	<div class="testimonials">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="section_title_container text-center">
						<div class="section_subtitle">only the best</div>
						<div class="section_title">testimonials</div>
					</div>
				</div>
			</div>
			<div class="row test_slider_container">
				<div class="col">

					<!-- Testimonials Slider -->
					<div class="owl-carousel owl-theme test_slider text-center">

						<!-- Testimonial Item -->
						<div class="owl-item">
							<div class="test_text">“Integer ut imperdiet erat. Quisque ultricies lectus tellus, eu tristique magna pharetra nec. Fusce vel lorem libero. Integer ex mi, facilisis sed nisi ut, vestibulum ultrices nulla. Aliquam egestas tempor leo.”</div>
							<div class="test_content">
								<div class="test_image"><img src="~/images/testimonials.jpg" alt=""></div>
								<div class="test_name">Christinne Smith</div>
								<div class="test_title">client</div>
							</div>
						</div>

						<!-- Testimonial Item -->
						<div class="owl-item">
							<div class="test_text">“Integer ut imperdiet erat. Quisque ultricies lectus tellus, eu tristique magna pharetra nec. Fusce vel lorem libero. Integer ex mi, facilisis sed nisi ut, vestibulum ultrices nulla. Aliquam egestas tempor leo.”</div>
							<div class="test_content">
								<div class="test_image"><img src="~/images/testimonials.jpg" alt=""></div>
								<div class="test_name">Christinne Smith</div>
								<div class="test_title">client</div>
							</div>
						</div>

						<!-- Testimonial Item -->
						<div class="owl-item">
							<div class="test_text">“Integer ut imperdiet erat. Quisque ultricies lectus tellus, eu tristique magna pharetra nec. Fusce vel lorem libero. Integer ex mi, facilisis sed nisi ut, vestibulum ultrices nulla. Aliquam egestas tempor leo.”</div>
							<div class="test_content">
								<div class="test_image"><img src="~/images/testimonials.jpg" alt=""></div>
								<div class="test_name">Christinne Smith</div>
								<div class="test_title">client</div>
							</div>
						</div>

					</div>

				</div>
			</div>
		</div>
	</div>

	<!-- Newsletter -->

	<div class="newsletter">
		<div class="newsletter_content">
			<div class="newsletter_image" style="background-image:url(images/newsletter.jpg)"></div>
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="section_title_container text-center">
							<div class="section_subtitle">only the best</div>
							<div class="section_title">Suscribete para un 20% de descuento</div>
						</div>
					</div>
				</div>
				<div class="row newsletter_container">
					<div class="col-lg-10 offset-lg-1">
						<div class="newsletter_form_container">
							<form asp-controller="Manager" asp-action="Newsletter" method="post">
								<input name="email" type="email" class="newsletter_input" required="required" placeholder="E-mail here">
								<button type="submit" class="newsletter_button">subscribe</button>
							</form>
						</div>
						<div class="newsletter_text">Al suscribirte obtendras un 20% de descuento en tu primera compra.</div>
					</div>
				</div>
			</div>
		</div>
	</div>