EvaShop/ViewModels/ShopingCartViewModel.cs
namespace EvaShop.ViewModels
{
    public class ShopingCartViewModel
    {
        public int Id { get; set; }
        public Guid ArticuloId { get; set; }
        public string Articulo { get; set; }
        public string ArticuloImagenes { get; set; }
        public bool ArticuloForMan { get; set; }
        public int Existencias { get; set; }
        public decimal PrecioDeVenta { get; set; }
        public int Cantidad { get; set; }
        public decimal SubTotal => PrecioDeVenta * Cantidad;
    }
}

EvaShop/Controllers/CheckoutController.cs
using AutoMapper;
using EvaShop.Data;
using EvaShop.Inputs;
using EvaShop.Models;
using EvaShop.Services;
using EvaShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EvaShop.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly ApplicationDbContext _appDbContext;
        private readonly IMapper _mapper;
        private readonly IEmailSender _emailSender;

        public CheckoutController(ApplicationDbContext appDbContext, 
            IMapper mapper, IEmailSender emailSender)
        {
            _appDbContext = appDbContext;
            _mapper = mapper;
            _emailSender = emailSender;
        }

        public IActionResult Index()
        {
            var billing = HttpContext.Session.GetIEnumerable<ShopingCartViewModel>("billing");
            ViewBag.CardModalClass = "";
            ViewBag.CardModalStyle = "";
            ViewBag.BodyClass = "";
            ViewBag.Backdrop = "";
            return View(billing);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CheckoutInput model)
        {
            var cliente = _mapper.Map<Cliente>(model);
            _appDbContext.Clientes.Add(cliente);
            var billing = HttpContext.Session.GetIEnumerable<ShopingCartViewModel>("billing");
            if (billing == null) return BadRequest();
            await _appDbContext.SaveChangesAsync();
            var pedido = new Pedido
            {
                ClienteId = cliente.Id,
                Fecha = new DateTime(),
                EstadoId = EstadosIds.EnProceso,
                Numero = new Guid().ToString(),
                TotalVenta = billing.Sum(b => b.SubTotal),
                DireccionDeEnvio = cliente.Direccion
            };
            var detalles = _mapper.Map<IEnumerable<Detalle>>(billing);
            pedido.Detellas = detalles.ToList();
            _appDbContext.Pedidos.Add(pedido);
            await _appDbContext.SaveChangesAsync();
            ViewBag.CardModalStyle = "display:block; padding-right:17px";
            ViewBag.CardModalClass = "show";
            ViewBag.BodyClass = "modal-open";
            ViewBag.Backdrop = "<div class='modal-backdrop fade show'></div>";
            ViewBag.PedidoId = pedido.Id;
            return View("Index", billing);
        }

        public IActionResult Confirm(string pedidoId)
        {
            var pedido = _appDbContext.Pedidos
                .Include(p=>p.Cliente)
                .FirstOrDefault(p => p.Id.ToString() == pedidoId);
            if(pedido == null) return NotFound();
            var billing = HttpContext.Session.GetIEnumerable<ShopingCartViewModel>("billing");
            if(billing == null) return NotFound();
            var msg = MessagesFormatter.Factura("Compra",billing);
            _emailSender.Notify(msg, pedido.Cliente.Email);
            pedido.EstadoId = EstadosIds.Facturado;
            _appDbContext.SaveChanges();
            HttpContext.Session.Remove("billing");
            HttpContext.Session.Remove("_Bag");
            return Ok();
        }
    }
}

EvaShop/Controllers/ProductController.cs
using AutoMapper;
using EvaShop.Data;
using EvaShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EvaShop.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _appDbContext;
        private readonly IMapper _mapper;

        public ProductController(ApplicationDbContext appDbContext, IMapper mapper)
        {
            _appDbContext = appDbContext;
            _mapper = mapper;
        }
        public IActionResult Index(string id)
        {
            var articulo = _appDbContext.Inventarios
                .Include(i=>i.Articulo)
                .ThenInclude(i=>i.SubCategoria)
                .ThenInclude(i=>i.Categoria)
                .FirstOrDefault(i=> i.ArticuloId.ToString() == id);

            return View(_mapper.Map<InventarioViewModel>(articulo));
        }
    }
}

EvaShop/Controllers/ShopingCartController.cs
using AutoMapper;
using EvaShop.Data;
using EvaShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EvaShop.Controllers
{
    public class ShopingCartController : Controller
    {
        private const string SessionKeyName = "_Bag";
        private readonly ApplicationDbContext _appDbContext;
        private readonly IMapper _mapper;

        public ShopingCartController(ApplicationDbContext appDbContext,
            IMapper mapper)
        {
            _appDbContext = appDbContext;
            _mapper = mapper;
        }
        public ActionResult Index()
        {
            var bag = HttpContext.Session.GetString(SessionKeyName);
            if (string.IsNullOrEmpty(bag)) return Redirect("Home");
            var myShopingCart = bag.Split(',').ToList();
            var group = myShopingCart.GroupBy(x => x).Select((x) => new
            {
                x.Key,
                x.ToList().Count
            }).ToList();
            var articulos = _appDbContext.Inventarios
                .Include(i=>i.Articulo)
                .ThenInclude(i=>i.SubCategoria)
                .ThenInclude(i=>i.Categoria)
                .ToList();
            

            articulos = articulos.Where(i => myShopingCart.Any(m => m == i.ArticuloId.ToString())).ToList();
            var result = _mapper.Map<IEnumerable<ShopingCartViewModel>>(articulos);
            foreach (var item in result)
            {
                item.Cantidad = group.FirstOrDefault(g => g.Key == item.ArticuloId.ToString())?.Count ?? 0;
            }
            HttpContext.Session.SetObject("billing",result);
            return View(result);
        }

        public IActionResult Delete(string id)
        {
            var billing = HttpContext.Session.GetIEnumerable<ShopingCartViewModel>("billing");
            if(billing == null) return BadRequest();
            billing = billing.Where(x=>x.ArticuloId.ToString() != id);
            HttpContext.Session.SetObject("billing",billing);
            var bag = HttpContext.Session.GetString(SessionKeyName);
            if(bag == null) return BadRequest();
            var myShopingCart = bag.Split(',').ToList();
            if(!myShopingCart.Any()) return BadRequest();
            myShopingCart = myShopingCart.Where(x=>x != id).ToList();
            bag = string.Join(",", myShopingCart);
            HttpContext.Session.SetString(SessionKeyName,bag);
            return View("Index",billing);
        }
    }
}

EvaShop/Views/ShopingCart/Index.cshtml
@using CatalogoWebApp.Services
@model IEnumerable<EvaShop.ViewModels.ShopingCartViewModel>
@inject IPathResolver PathResolver 
@section Header{
	<link rel="stylesheet" type="text/css" href="~/plugins/malihu-custom-scrollbar/jquery.mCustomScrollbar.css"> 
	<link rel="stylesheet" type="text/css" href="~/plugins/jquery-ui-1.12.1.custom/jquery-ui.css">
	<link rel="stylesheet" type="text/css" href="~/css/cart.css">
	<link rel="stylesheet" type="text/css" href="~/css/cart_responsive.css">
}


@{
	ViewData["Title"] = "ShopingCart";
}

	<!-- Cart -->

<div class="cart_container">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="cart_title">your shopping cart</div>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<div class="cart_bar d-flex flex-row align-items-center justify-content-start">
					<div class="cart_bar_title_name">Product</div>
					<div class="cart_bar_title_content ml-auto">
						<div class="cart_bar_title_content_inner d-flex flex-row align-items-center justify-content-end">
							<div class="cart_bar_title_price">Price</div>
							<div class="cart_bar_title_quantity">Quantity</div>
							<div class="cart_bar_title_total">Total</div>
							<div class="cart_bar_title_button"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			@foreach (var item in Model)
			{
				<div class="col">
					<div class="cart_products">
						<ul>
							<li class=" cart_product d-flex flex-md-row flex-column align-items-md-center align-items-start justify-content-start">
								<!-- Product Image -->
								<div class="cart_product_image">
									<img style="height: 120px; width: 120px" src="@PathResolver.GetUrl(@item.ArticuloImagenes)" alt="articulo">
								</div>
								<!-- Product Name -->
								<div class="cart_product_name"><a asp-controller="Product" asp-action="Index" asp-route-Id="@item.ArticuloId">@item.Articulo</a></div>
								<div class="cart_product_info ml-auto">
									<div class="cart_product_info_inner d-flex flex-row align-items-center justify-content-md-end justify-content-start">
										<!-- Product Price -->
										<div class="cart_product_price">@item.PrecioDeVenta</div>
										<!-- Product Quantity -->
										<div class="product_quantity_container">
											<div class="product_quantity clearfix">
												<input id="quantity_input" type="text" pattern="[0-9]*" value="@item.Cantidad" maxlength="@item.Existencias" disabled>
												@*<div class="quantity_buttons">
													<div id="quantity_inc_button" class="quantity_inc quantity_control"><i class="fa fa-caret-up" aria-hidden="true"></i></div>
													<div id="quantity_dec_button" class="quantity_dec quantity_control"><i class="fa fa-caret-down" aria-hidden="true"></i></div>
												</div>*@
											</div>
										</div>
										<!-- Products Total Price -->
										<div class="cart_product_total">@item.SubTotal</div>
										<!-- Product Cart Trash Button -->
										<div class="cart_product_button">
											<a class="cart_product_remove" asp-controller="ShopingCart" asp-action="Delete" asp-route-id="@item.ArticuloId"><img src="~/images/trash.png" alt=""></a>
										</div>
									</div>
								</div>
							</li>
						</ul>
					</div>
				</div>
			}
		</div>
		<div class="row">
			<div class="col">
				<div class="cart_control_bar d-flex flex-md-row flex-column align-items-start justify-content-start">
					@*<button class="button_clear cart_button">clear cart</button>
					<button class="button_update cart_button">update cart</button>*@
					<a class="cart_button ml-md-auto" asp-controller="Products" asp-action="Index" style="padding-top: 1.3%">Continuar comprando</a>
				</div>
			</div>
		</div>
		<div class="row cart_extra">
			<!-- Cart Coupon -->
			<div class="col-lg-6">
				<div class="cart_coupon">
					<div class="cart_title">coupon code</div>
					<form action="#" class="cart_coupon_form d-flex flex-row align-items-start justify-content-start" id="cart_coupon_form">
						<input type="text" class="cart_coupon_input" placeholder="Coupon code" required="required">
						<button class="button_clear cart_button_2">apply coupon</button>
					</form>
				</div>
			</div>
			<!-- Cart Total -->
			<div class="col-lg-5 offset-lg-1">
				<div class="cart_total" style="margin-bottom: 10px"> 
					<div class="cart_title">cart total</div>
					<ul>
						<li class="d-flex flex-row align-items-center justify-content-start">
							<div class="cart_total_title">Subtotal</div>
							<div class="cart_total_price ml-auto">$35.00</div>
						</li>
						<li class="d-flex flex-row align-items-center justify-content-start">
							<div class="cart_total_title">Shipping</div>
							<div class="cart_total_price ml-auto">$5.00</div>
						</li>
						<li class="d-flex flex-row align-items-center justify-content-start">
							<div class="cart_total_title">Total</div>
							<div class="cart_total_price ml-auto">$40.00</div>
						</li>
					</ul>
				</div>
			</div>
			<a class="cart_total_button" asp-controller="Checkout" asp-action="Index" style="font-size: 15px;padding-top: 1%">Proceder a pagar</a>
		</div>
	</div>
</div>

@section Scripts
{
	<script src="js/cart_custom.js"></script>
}