EvaShop/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace EvaShop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EvaShop/Controllers/ManagerController.cs
using EvaShop.Services;
using Microsoft.AspNetCore.Mvc;

namespace CatalogoWebApp.Controllers
{
    public class ManagerController : Controller
    {
        private readonly IEmailSender _emailSender;
        private const string SessionKeyName = "_Name";
        private const string Error = "_Error";

        public ManagerController(IEmailSender emailSender)
        {
            _emailSender = emailSender;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(string user, string password)
        {
            if (user == "Admin" && password == "Catolica10")
            {
                HttpContext.Session.SetString(SessionKeyName, "Admin");
                return Redirect("/Inventarios");
            }
            HttpContext.Session.SetString(Error,"Usuario o contraseña incorrecta");
            return Redirect("/Home");

        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove(SessionKeyName);
            HttpContext.Session.Remove(Error);
            return Redirect("/Home");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Newsletter(string email)
        {
            const string msg = "<h1 style='text-align: center'>Felicidades tienes un descuento del 20%<h1>";
            return Redirect(_emailSender.Notify(msg, email) ? "/Home" : "/Contact");
        }

        //GET IN TOUCH
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult GetInTouch(string name,string email, string subject, string body)
        {
            var msg = email + ": " + body; 
            return Redirect(_emailSender.Notify(msg,_emailSender.GetEmail(),subject) ? "/Home" : "/Contact");
        }
    }
}

EvaShop/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EvaShop.Data;
using EvaShop.Models;

namespace EvaShop.Controllers
{
    public class PedidosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PedidosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pedidos
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Pedidos.Include(p => p.Cliente).Include(p => p.Estado);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Pedidos/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .Include(p => p.Cliente)
                .Include(p => p.Estado)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // GET: Pedidos/Create
        public IActionResult Create()
        {
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Id");
            ViewData["EstadoId"] = new SelectList(_context.Estados, "Id", "Id");
            return View();
        }

        // POST: Pedidos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Numero,Descripcion,Fecha,TotalVenta,DireccionDeEnvio,EstadoId,ClienteId")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                pedido.Id = Guid.NewGuid();
                _context.Add(pedido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Id", pedido.ClienteId);
            ViewData["EstadoId"] = new SelectList(_context.Estados, "Id", "Id", pedido.EstadoId);
            return View(pedido);
        }

        // GET: Pedidos/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Id", pedido.ClienteId);
            ViewData["EstadoId"] = new SelectList(_context.Estados, "Id", "Id", pedido.EstadoId);
            return View(pedido);
        }

        // POST: Pedidos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Numero,Descripcion,Fecha,TotalVenta,DireccionDeEnvio,EstadoId,ClienteId")] Pedido pedido)
        {
            if (id != pedido.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Id", pedido.ClienteId);
            ViewData["EstadoId"] = new SelectList(_context.Estados, "Id", "Id", pedido.EstadoId);
            return View(pedido);
        }

        // GET: Pedidos/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .Include(p => p.Cliente)
                .Include(p => p.Estado)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Pedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Pedidos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Pedidos'  is null.");
            }
            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido != null)
            {
                _context.Pedidos.Remove(pedido);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(Guid id)
        {
          return (_context.Pedidos?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

EvaShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Mvc.TagHelpers
@inject IHttpContextAccessor HttpContextAccessor

@{
    var bag = HttpContextAccessor.HttpContext?.Session.GetString("_Bag");
    bag = string.IsNullOrEmpty(bag) ? "0" : bag.Split(',').Length.ToString();

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - EvaShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap4/bootstrap.min.css">
    <link rel="stylesheet" href="~/plugins/font-awesome-4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="~/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="~/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="~/plugins/OwlCarousel2-2.2.1/animate.css">
    <link rel="stylesheet" type="text/css" href="~/plugins/colorbox/colorbox.css">
    <link rel="stylesheet" type="text/css" href="~/css/main_styles.css">
    <link rel="stylesheet" type="text/css" href="~/css/responsive.css">
    @await RenderSectionAsync("Header", required: false)
</head>
<body class="@ViewBag.BodyClass">
    <div class="super_container">

        <!-- Header -->

        <header class="header">
            <div class="header_inner d-flex flex-row align-items-center justify-content-start">
                <div class="logo"><img style="width:75px; height:50px" src="~/images/Evalogo.png"></div>
                <nav class="main_nav">
                    <ul>
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Categories" asp-action="Index">Categorias</a></li>
                        <li><a asp-controller="Products" asp-action="Index" asp-route-forman="false">Mujeres</a></li>
                        <li><a asp-controller="Products" asp-action="Index" asp-route-forman="true">Hombres</a></li>
                        <li><a asp-controller="Home" asp-action="AboutUs">Quiénes somos</a></li>
                        <li><a asp-controller="Contact" asp-action="Index">Contactanos</a></li>
                    </ul>
                </nav>
                <div class="header_content ml-auto">
                    <div class="shopping">
                        <!-- Cart -->
                        <a asp-controller="ShopingCart" asp-action="Index">
                            <div class="cart">
                                <img src="~/images/shopping-bag.svg" alt="">
                                <div class="cart_num_container">
                                    <div class="cart_num_inner">
                                        <div id="cart_num" class="cart_num">
                                            @bag
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <!-- Star -->
                        <a href="#">
                            <div class="star">
                                <img src="~/images/star.svg" alt="">
                                <div class="star_num_container">
                                    <div class="star_num_inner">
                                        <div class="star_num">0</div>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <!-- Avatar -->
                        <a href="#">
                            <div class="avatar" type="button" data-toggle="modal" data-target="#exampleModal">
                                <img src="~/images/avatar.svg" alt="">
                            </div>
                        </a>
                    </div>
                </div>

                <div class="burger_container d-flex flex-column align-items-center justify-content-around menu_mm"><div></div><div></div><div></div></div>
            </div>
        </header>

        <!-- Menu -->

        <div class="menu d-flex flex-column align-items-end justify-content-start text-right menu_mm trans_400">
            <div class="menu_close_container"><div class="menu_close"><div></div><div></div></div></div>
            <div class="logo menu_mm"><a href="#">Eva</a></div>
            <div class="search">
                <form action="#">
                    <input type="search" class="search_input menu_mm">
                    <button type="submit" id="search_button_menu" class="search_button menu_mm"><img class="menu_mm" src="~/images/magnifying-glass.svg" alt=""></button>
                </form>
            </div>
            <nav class="menu_nav">
                <ul class="menu_mm">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Categories" asp-action="Index">Categorias</a></li>
                    <li><a asp-controller="Products" asp-action="Index" asp-route-forman="false">Mujeres</a></li>
                    <li><a asp-controller="Products" asp-action="Index" asp-route-forman="true">Hombres</a></li>
                    <li><a asp-controller="Home" asp-action="AboutUs">Quiénes somos</a></li>
                    <li><a asp-controller="Contact" asp-action="Index">Contactanos</a></li>
                </ul>
            </nav>
        </div>
        <div>
            <main>
                @RenderBody()
            </main>
        </div>

        <!-- Footer -->

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col text-center">
                        <div class="footer_logo"><a href="#">Eva</a></div>
                        <nav class="footer_nav">
                            <ul>
                                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                                <li><a asp-controller="Categories" asp-action="Index">Categorias</a></li>
                                <li><a asp-controller="Products" asp-action="Index" asp-route-forman="false">Mujeres</a></li>
                                <li><a asp-controller="Products" asp-action="Index" asp-route-forman="true">Hombres</a></li>
                                <li><a asp-controller="Home" asp-action="AboutUs">Quiénes somos</a></li>
                                <li><a asp-controller="Contact" asp-action="Index">Contactanos</a></li>
                            </ul>
                        </nav>
                        <div class="footer_social">
                            <ul>
                                <li><a href="https://wa.me/message/NYT6X3EDZCGPL1"><i class="fa fa-whatsapp" aria-hidden="true"></i></a></li>
                                <li><a href="https://www.instagram.com/accounts/login/?next=/evaunderwear22/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                <li><a href="https://www.facebook.com/people/Eva-Underweare/100081220613977/"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            </ul>
                        </div>
                        <div class="copyright">
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="" target="_blank">Eva</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="background: transparent;border: transparent">
            <div class="modal-body">
                <div class="login">
                    <div class="login-triangle"></div>

                    <h2 class="login-header">Log in</h2>

                    <form asp-controller="Manager" asp-action="Login" role="form" method="post" class="login-container">
                        <p><input name="user" type="text" placeholder="User"></p>
                        <p><input name="password" type="password" placeholder="Password"></p>
                        <p><input type="submit" value="Log in"></p>
                        <p><input type="submit" value="Close" data-dismiss="modal"></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap4/popper.js"></script>
    <script src="~/lib/bootstrap4/bootstrap.min.js"></script>
    <script src="~/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
    <script src="~/plugins/easing/easing.js"></script>
    <script src="~/plugins/colorbox/jquery.colorbox-min.js"></script>
    <script src="~/plugins/parallax-js-master/parallax.min.js"></script>
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

    @await RenderSectionAsync("Bootom",required:false)
</body>
</html>

EvaShop/Views/Shared/_LayoutAdmin.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - EvaShop</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/plugins/font-awesome-4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/main_styles.css">
    <link rel="stylesheet" type="text/css" href="~/css/responsive.css">
    @await RenderSectionAsync("Header", required: false)
</head>
<body class="@ViewBag.BodyClass">
    <div>

        <!-- Header -->

        <header class="header" style="margin-bottom: 25px">
            <div class="header_inner d-flex flex-row align-items-center justify-content-start">
                <div class="logo"><img style="width:75px; height:50px" src="~/images/Evalogo.png" alt="logo"></div>
                <nav class="main_nav">
                    <ul>
                        <li><a asp-controller="Inventarios" asp-action="Index">Inventario</a></li>
                        <li><a asp-controller="Articulos" asp-action="Index">Articulos</a></li>
                        <li><a asp-controller="Pedidos" asp-action="Index">Pedidos</a></li>
                        <li><a asp-controller="Manager" asp-action="Logout">Logout</a></li>
                    </ul>
                </nav>
            </div>
        </header>

        <div>
            <main>
                @RenderBody()
            </main>
        </div>

        <!-- Footer -->

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col text-center">
                        <div class="footer_logo"><a href="#">Eva</a></div>
                        <div class="footer_social">
                            <ul>
                                <li><a href=""><i class="fa fa-whatsapp" aria-hidden="true"></i></a></li>
                                <li><a href="https://www.instagram.com/accounts/login/?next=/evaunderwear22/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                <li><a href="https://www.facebook.com/people/Eva-Underweare/100081220613977/"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            </ul>
                        </div>
                        <div class="copyright">
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="" target="_blank">Eva</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap4/popper.js"></script>
    <script src="~/lib/bootstrap4/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

    @await RenderSectionAsync("Bootom",required:false)
</body>
</html>